# This compose file will start a peer node, a membersrvc,
# and an sdk environment for testing

version: '2'

services:
  membersrvc:
    container_name: membersrvc
    image: hyperledger/fabric-membersrvc
    restart: unless-stopped
    expose:
      - "7054"
    command: membersrvc

  peer:
    container_name: peer
    image: hyperledger/fabric-peer
    restart: unless-stopped
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_NETWORKID=dev
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=vp0
      - CORE_SECURITY_ENABLED=true
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
      - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=noops
    expose:
      - "7050"
      - "7051"
      - "7052"
      - "7053"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - membersrvc
    command: sh -c "sleep 5; peer node start --peer-chaincodedev"

  sdk-py:
    container_name: sdk-py
    build: .
    image: hyperledger/fabric-sdk-py
    environment:
      - PEER_GRPC_ADDR=peer:7051
      - MEMBERSRVC_GRPC_ADDR=membersrvc:7054
    links:
      - membersrvc
      - peer
    command: sh -c "while true; do sleep 1000; done"
