# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
  branches:
    include:
      - master
pr:
  branches:
    include:
      - master
pool:
  vmImage: ubuntu-18.04

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - script: pip install virtualenv
    displayName: Install VirtualEnv
  - script: |
      sudo snap install couchdb
      sudo snap set couchdb admin=admin
      sudo snap start couchdb
      sudo snap connect couchdb:mount-observe
      sudo snap connect couchdb:process-control
  - script: sleep 5
  - script: curl localhost:5984
    displayName: Install CouchDB
  - script: make check
    displayName: Run Checks
